### ISSUE TITLE
Repeating weekly event with end date returns true despite being out of start end date range

### ISSUE THREAD

**Issue by murugaratham** [jamesstill/ScheduleWidget#27]
I was trying out the Sample MVC project to create a recurring event:

Reproduce:
Start 1st Jul
End 1st Aug

Repeat weekly, Mon - Fri

When i navigate beyond 1st Aug, `scheduleDTO.Schedule.Occurrences(range)` returns the next weekday after 1st aug

**Comment by Bally77** [comment]
Hi 

Did you ever get this sorted.  I am trying to use schedule widget for recurring events but the scheduling seems to take no notice of the start/end date of the event.  I have downloaded the sample MVC and it is the same in that when you create a daily/weekly event( the only two I have tested) it creates event occurences forever even if I have a start and end date

Any help much appreciated

Balram

**Comment by jamesstill** [comment]
Hello Balram, the start and end dates are optional by design in the
scheduling engine. You can check out the sample app
<https://github.com/jamesstill/ScheduleWidget/tree/master/ScheduleWidgetSampleProject>
for help on this topic. The street cleaning unit test
<https://github.com/jamesstill/ScheduleWidget/blob/master/ScheduleWidget/ScheduleWidget.UnitTest/StreetCleaningTests.cs>
shows how to feed in a start/end date.  The simple date unit test
<https://github.com/jamesstill/ScheduleWidget/blob/master/ScheduleWidget/ScheduleWidget.UnitTest/SimpleDateTest.cs>
shows an example of leaving them out. Hope this helps.

--
James Still
http://www.squarewidget.com
james@squarewidget.com
Mobile: +1.503.475.3808
Twitter: @squarewidget

**Comment by Bally77** [comment]
Hi James

thanks for that, it's done the trick nicely

Bal
